# Generated by Django 5.1.3 on 2024-12-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_tarea_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
